name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.1'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get $(pwd)/waterlog

    - name: Run tests
      working-directory: ./waterlog
      run: flutter test
